change t_sne to _t_sne to work with sklearn 0.24.1
As of sklearn 0.24.1 (Python 3.8.5), calling manifold.t_sne raises an AttributeError: module 'sklearn.manifold' has no attribute 't_sne'.

Changing it to manifold._t_sne seems to work.